//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<int> fabricante { get; set; }
        public Nullable<decimal> preco { get; set; }
    
        public virtual fabricante fabricante1 { get; set; }
    }
}
